### ISSUE TITLE
Cannot read property 'onEnterDown' of undefined

### ISSUE THREAD

**Issue by sasanazizi** [dead/react-key-navigation#2]
after i run tizen project in tizen studio and press "ok" button on emulator's control this happens! 
help help !

**Comment by dead** [comment]
~~You need to set the onEnterDown property in the focusable component.~~
~~Example: `<Focusable onEnterDown={() => console.log('click ok')} />`~~

Hm, it seems the element that is firing this event is undefined... Not really sure what can cause this.
Can you send me an example where this happen? Or this happen even in the youtube example?

**Comment by itsmh** [comment]
Hi dead (even though I dont like using it),
I've checked the library seems the build is older than the sources, The `getLastFromPath` function does not exist in `enter-down` function firing. the **enter-down** event in the _build_ differs from _src_.

I think a fresh build will fix it, actually it causes the packages installed by **npm** does not work properly, building manually and using it works fine.

thanks for the great work btw

**Comment by dead** [comment]
Fixed it, thanks 😄
@sasanazizi can you update the library and test it now?
