### ISSUE TITLE
Unable to retain last focused element

### ISSUE THREAD

**Issue by skhulbe** [dead/react-key-navigation#4]
Hi.. I am using this library for one of my project and really enjoying using this.

I am facing difficulty in retaining the last focused list-item. For example, say in youtube app example, if focus is on the 3rd element of HorizontalList-1 and we move down to HorizontalList-3 and come back to List 1. The focus moves to the first element.

How to retain that focus to the 3rd element?

**Comment by metoikos** [comment]
Same here. Look through the source but couldn't spot the behavior.

**Comment by dead** [comment]
Hey guys, this is not implemented yet. It's possible to implement this by extending the current VerticalList/HorizontalList...
Just store the last focused child and change the getDefaultFocus to return that child.

**Comment by metoikos** [comment]
Thanks @dead. I managed to achieve what I want with this class. I hope it helps others.
```
import {HorizontalList} from 'react-key-navigation';

class CustomHorizontalList extends HorizontalList {
	constructor(props, context) {
		super(props, context);

		this.lastFocus = null;
	}

	getNextFocus(direction, focusedIndex) {
		if (direction !== 'left' && direction !== 'right') {
			return super.getNextFocus(direction, this.indexInParent);
		}

		let nextFocus = null;
		if (direction === 'left') {
			nextFocus = this.previousChild(focusedIndex);
		} else if (direction === 'right') {
			nextFocus = this.nextChild(focusedIndex);
		}

		if (!nextFocus) {
			return super.getNextFocus(direction, this.indexInParent);
		}

		if (nextFocus.isContainer()) {
			return nextFocus.getDefaultFocus();
		}

		this.lastFocus = nextFocus;

		return nextFocus;
	}

	getDefaultFocus() {
		if (this.lastFocus) return this.lastFocus;
		return super.getDefaultFocus();
	}
}

export default CustomHorizontalList;
```

**Comment by metoikos** [comment]
Thanks @dead. I managed to achieve what I want with this class. I hope it helps others.

```
import {HorizontalList} from 'react-key-navigation';


class CustomHorizontalList extends HorizontalList {
	constructor(props, context) {
		super(props, context);

		this.lastFocus = null;
	}

	getNextFocus(direction, focusedIndex) {
		const nextFocus = super.getNextFocus(direction, focusedIndex);
		if (direction !== 'left' && direction !== 'right') {
			return nextFocus;
		}

		if (nextFocus) this.lastFocus = nextFocus;

		return nextFocus;
	}
	
	getDefaultFocus() {
		if (this.lastFocus) return this.lastFocus;
		return super.getDefaultFocus();
	}
}

export default CustomHorizontalList;

```

**Comment by skhulbe** [comment]
Thanks, guys. I was doing the same, just wanted to cross-check if there is some other way to achieve the same.

**Comment by dead** [comment]
Now you should be able to retain the last focused elements using `retainLastFocus={true}` 😄
