### ISSUE TITLE
Set focus programmatically

### ISSUE THREAD

**Issue by johneisenheim** [dead/react-key-navigation#5]
Hi @dead,
first of all thank you for your awesome work! I've seen that your focus system creates a sort of tree of rendered focusable component, distinguished by a progressive index. My question is: if I have 3 components (a Vertical List, an Horizontal List and a Vertical List again in that order), if horizontal list is focused can I give focus to the second Vertical List when the enter key is pressed?

Thank you!

**Comment by dead** [comment]
Just implemented this feature 😄, you can see how it work in the youtube example... https://github.com/dead/react-key-navigation/blob/3091d0dd474ff1e2bd5fe65b925452b0a45f3a51/examples/youtube-react-tv/src/Search.js#L23 and https://github.com/dead/react-key-navigation/blob/3091d0dd474ff1e2bd5fe65b925452b0a45f3a51/examples/youtube-react-tv/src/Sidebar.js#L50
But basically you can set a id to a focusable component and then use the navigation.forceFocus(id) to change the focus to the component.
(All events  onBlur, onFocus, onEnterDown now have an "event" and "navigation" parameter)

**Comment by johneisenheim** [comment]
Fantastic!
Thank you so much!
