### ISSUE TITLE
this.root.getDefaultFocus is not a function

### ISSUE THREAD

**Issue by johneisenheim** [dead/react-key-navigation#6]
Hi @dead,
After upgrading your library, this error appears:

`this.root.getDefaultFocus is not a function`

Can you help me (again)? 😄 

<img width="1085" alt="schermata 2018-07-04 alle 11 03 41" src="https://user-images.githubusercontent.com/1299478/42267694-014b9594-7f7a-11e8-8f77-6630362db9cd.png">

**Comment by johneisenheim** [comment]
Trying to fix the error, I found a sort of solution. In Navigation, the `render` method is written as follow:

```
render(){
    return (
      <VerticalList ref={element => this.root = element}>
        {this.props.children}
      </VerticalList>
    )
}
```
That being said, the `setRoot()`method is useless, and everything is working now.

**Comment by dead** [comment]
Thanks 😄
