### ISSUE TITLE
Force focus back to parent

### ISSUE THREAD

**Issue by johneisenheim** [dead/react-key-navigation#7]
Hi @dead ,
I'm facing the following issue: let's assume I have something like 

```
<Navigator>
   <HorizontalList>
         <Menu>
              <VerticalList>
                      {...}
             </VerticalList>
        </Menu>
        <HorizontalList focusedId='h-list' retainFocus={true}>
               {...}
        </HorizontalList>
        <Modal>
            <HorizontalList focusedId='modal'>
            </HorizontalList>
       </Modal>
   </HorizontalList>
</Navigator>
```

Let's assume that Modal component can be rendered with a boolean property: if this prop is `true`, the component is rendered, `null` otherwise.

In `h-list` items, I have: 

```
onEnterDown = (e, nav) => {
    openModal(true);
    nav.forceFocus('modal');
}
```
In Modal component, when I try to focus the `h-list` back it's seems that the Modal component itself is still present both in `treePath` and `focusableComponents`. So when I try to navigate in h-list component, the last focused item is ok, but when I press left or right focus disappear (logging your code, the modal is still focused, and the `next` item is a modal focusable item). Any chance to investigate on this problem?

Thank you again!

**Comment by dead** [comment]
When you try to focus back to the h-list, you close the modal? Because it should unmount the HorizontalList inside of it.
Well, I think for modal we need to restrict the focusable zone to only the modal, unless you force the focus in other zone.

**Comment by johneisenheim** [comment]
Yes! Modal is closed (the component renders `null`). But when I go back, I think it should remove Horizontal List component from tree path and from focusableComponents (I guess)...

**Comment by johneisenheim** [comment]
A sort of workaround to make the focus stay in an Horizontal List is the following:

```
class HorizontalList extends Focusable {
  constructor(props) {
    super(props)
    this.restInFocus = props.restInFocus ? props.restInFocus : false;
  }
  getNextFocus = (direction, focusedIndex) => {
    if (direction !== 'left' && direction !== 'right') {
      if (this.restInFocus)
        return
      return super.getNextFocus(direction, this.indexInParent);
    }
...
```
If we pass the prop `restInFocus` in the Modal horizontal list, the focus stay in the horizontal list's items. So, first problem is kindly solved.

**Comment by johneisenheim** [comment]
Hi @dead, after some investigations, when we remove components from DOM the Navigation Object is not updated, so that the Container and its focusable elements remains and are potentially focusable, despite they are not visible because are not mounted. Is there a way to fix? 

Thank you

**Comment by rinaldoleone** [comment]
Hi @dead , we have solved this problem. We tried to submit a pull request, but we are unable to push a branch.

**Comment by dead** [comment]
@rinaldoleone thanks! I didn't had much time to work on this...
Try creating a fork, push to it and then submit the pull request via github.
